<?php

namespace Modules\Mailbox\Services\Imap;

use Illuminate\Support\Carbon;
use Webklex\PHPIMAP\Address;
use Webklex\PHPIMAP\Attachment;
use Webklex\PHPIMAP\Message;

/**
 * A webklex message, flattened into something the rest of Mailbox can hold.
 *
 * Webklex's `Message` is lazy — reading a property can open a socket — so a job
 * or a controller holding one has no way to tell whether it is doing network
 * work, and a test holding one cannot exist without a server. Everything is
 * resolved here, and a `RemoteMessage` comes out with none of the library left
 * on it.
 *
 * This lives apart from `WebklexMailbox` because there are now two sources of a
 * webklex message and only one of them is a mailbox. `Message::fromString()`
 * parses the raw RFC822 a Cloudflare Email Worker posts, with no connection and
 * no folder behind it, and the result needs exactly the same flattening. The
 * alternative was a second mapper that would have started identical and then
 * drifted — the copy under test staying right, the other quietly losing the
 * `In-Reply-To` trimming that makes replies thread.
 */
class WebklexHydrator
{
    /**
     * @param  int  $uid  The message's UID, or 0 where the concept does not apply.
     *                    A pushed message has no UID: nothing polls it, no cursor
     *                    resumes against it, and `emails.message_id` is what makes
     *                    it unique either way.
     */
    public function hydrate(Message $message, int $uid): RemoteMessage
    {
        $from = $message->getFrom()?->first();
        $flags = $this->flags($message);

        return new RemoteMessage(
            uid: $uid,
            messageId: $this->messageId($message, $uid),
            inReplyTo: $this->truncate(trim($this->header($message->getInReplyTo()) ?? '', '<>'), 255),
            subject: $this->truncate($this->header($message->getSubject()), 255),
            fromName: $from instanceof Address ? $this->truncate($from->personal, 190) : null,
            fromEmail: $from instanceof Address ? $this->truncate($from->mail, 190) : null,
            to: $this->mails($message->getTo()),
            cc: $this->mails($message->getCc()),
            textBody: $message->getTextBody() ?: null,
            htmlBody: $message->getHTMLBody() ?: null,
            receivedAt: $this->date($message),
            seen: in_array('seen', $flags, true),
            flagged: in_array('flagged', $flags, true),
            attachments: $this->attachments($message),
        );
    }

    /**
     * The message's own identity, or one derived from what it does carry.
     *
     * A Message-ID is required by RFC 5322 and is nonetheless sometimes absent,
     * usually from something generated by a script. Falling back to the UID
     * would be wrong: a UID means something only within one UIDVALIDITY, so a
     * rebuilt mailbox would hand the same message a new identity and store it
     * twice. A hash of the headers that do exist survives that — and survives
     * the pushed case too, where the UID is 0 for every message and a fallback
     * that leaned on it would collapse the whole inbox into one row.
     */
    private function messageId(Message $message, int $uid): string
    {
        $raw = trim((string) $message->getMessageId(), " \t\n\r\0\x0B<>");

        if ($raw !== '') {
            return mb_substr($raw, 0, 255);
        }

        $fingerprint = hash('sha256', implode('|', [
            (string) $message->getSubject(),
            (string) $message->getFrom(),
            (string) $message->getDate(),
            (string) $message->getSize(),
            $uid,
        ]));

        return 'sha256-'.$fingerprint.'@kargah.invalid';
    }

    /**
     * The message's flags, lowercased, or none.
     *
     * A parsed message has no flags — flags are IMAP state, and there is no
     * server holding any for a message that was handed to us over HTTP. Webklex
     * answers that case with an empty attribute rather than an error, but it is
     * read defensively because the alternative is a parse failure turning into a
     * 500, which the Worker reads as "retry" and the sender repeats for days.
     */
    private function flags(Message $message): array
    {
        return rescue(
            fn (): array => array_map('strtolower', $message->getFlags()->all()),
            [],
            false,
        );
    }

    /**
     * @return list<RemoteAttachment>
     */
    private function attachments(Message $message): array
    {
        $out = [];

        /** @var Attachment $attachment */
        foreach ($message->getAttachments() as $attachment) {
            $name = trim((string) $attachment->getName());

            if ($name === '') {
                continue;
            }

            $size = $attachment->getSize();

            $out[] = new RemoteAttachment(
                filename: mb_substr($name, 0, 255),
                mime: $this->truncate($attachment->getMimeType(), 190),
                sizeBytes: $size === null ? null : (int) $size,
                contentId: $this->truncate((string) $attachment->getId(), 190),
                partNumber: $this->truncate((string) $attachment->getPartNumber(), 20),
            );
        }

        return $out;
    }

    private function date(Message $message): ?Carbon
    {
        $date = $message->getDate()?->first();

        return $date instanceof \DateTimeInterface ? Carbon::instance($date) : null;
    }

    /**
     * @return list<string>
     */
    private function mails(mixed $attribute): array
    {
        $out = [];

        foreach ($attribute?->all() ?? [] as $address) {
            if ($address instanceof Address && $address->mail !== '') {
                $out[] = $address->mail;
            }
        }

        return array_values(array_unique($out));
    }

    private function header(mixed $attribute): ?string
    {
        $value = trim((string) $attribute);

        return $value === '' ? null : $value;
    }

    private function truncate(?string $value, int $length): ?string
    {
        if ($value === null || trim($value) === '') {
            return null;
        }

        // Column widths, not display widths. A subject longer than its column
        // must not take the whole message down with it.
        return mb_substr($value, 0, $length);
    }
}
