<?php

namespace Modules\Mailbox\Services\Imap;

use Illuminate\Support\Carbon;
use Webklex\PHPIMAP\Address;
use Webklex\PHPIMAP\Attachment;
use Webklex\PHPIMAP\Folder;
use Webklex\PHPIMAP\Message;

/**
 * One open folder on a real server.
 *
 * Every message is flattened into a `RemoteMessage` before it leaves this
 * class. Webklex's `Message` is lazy — reading a property can open a socket —
 * so a job holding one has no way to tell whether it is doing network work, and
 * a test holding one cannot exist without a server. Resolving everything here
 * is what keeps the rest of the sync honest about where the network is.
 */
class WebklexMailbox implements MailboxConnection
{
    public function __construct(
        private readonly string $account,
        private readonly Folder $folder,
    ) {}

    public function state(): MailboxState
    {
        try {
            $status = $this->folder->examine();
        } catch (\Throwable $e) {
            throw MailboxUnavailable::failed($this->account, $e->getMessage());
        }

        // A server that answers EXAMINE without UIDVALIDITY is out of spec, and
        // inventing a value would let a cursor survive a rebuild it must not
        // survive. Refuse to sync rather than sync against a number we guessed.
        if (! isset($status['uidvalidity'], $status['uidnext'])) {
            throw MailboxUnavailable::failed(
                $this->account,
                'the folder reported no UIDVALIDITY or UIDNEXT, so no cursor can be trusted against it',
            );
        }

        return new MailboxState((int) $status['uidvalidity'], (int) $status['uidnext']);
    }

    public function fetch(int $fromUid, int $toUid): iterable
    {
        if ($toUid < $fromUid) {
            return [];
        }

        try {
            $messages = $this->folder->query()
                ->whereUid($fromUid.':'.$toUid)
                ->setFetchOrderAsc()
                ->setFetchBody(true)
                ->setFetchFlags(true)
                // One malformed message in the window must not cost the other
                // ninety-nine. Soft fail collects the error and returns the
                // rest; the window is marked done either way, because a message
                // this library cannot parse will not parse on the next tick.
                ->softFail()
                ->get();
        } catch (\Throwable $e) {
            throw MailboxUnavailable::failed($this->account, $e->getMessage());
        }

        $out = [];

        foreach ($messages as $message) {
            $out[] = $this->hydrate($message);
        }

        usort($out, fn (RemoteMessage $a, RemoteMessage $b) => $a->uid <=> $b->uid);

        return $out;
    }

    private function hydrate(Message $message): RemoteMessage
    {
        $uid = (int) $message->getUid();
        $from = $message->getFrom()?->first();
        $flags = array_map('strtolower', $message->getFlags()->all());

        return new RemoteMessage(
            uid: $uid,
            messageId: $this->messageId($message, $uid),
            inReplyTo: $this->truncate(trim($this->header($message->getInReplyTo()) ?? '', '<>'), 255),
            subject: $this->truncate($this->header($message->getSubject()), 255),
            fromName: $from instanceof Address ? $this->truncate($from->personal, 190) : null,
            fromEmail: $from instanceof Address ? $this->truncate($from->mail, 190) : null,
            to: $this->mails($message->getTo()),
            cc: $this->mails($message->getCc()),
            textBody: $message->getTextBody() ?: null,
            htmlBody: $message->getHTMLBody() ?: null,
            receivedAt: $this->date($message),
            seen: in_array('seen', $flags, true),
            flagged: in_array('flagged', $flags, true),
            attachments: $this->attachments($message),
        );
    }

    /**
     * The message's own identity, or one derived from what it does carry.
     *
     * A Message-ID is required by RFC 5322 and is nonetheless sometimes absent,
     * usually from something generated by a script. Falling back to the UID
     * would be wrong: a UID means something only within one UIDVALIDITY, so a
     * rebuilt mailbox would hand the same message a new identity and store it
     * twice. A hash of the headers that do exist survives that.
     */
    private function messageId(Message $message, int $uid): string
    {
        $raw = trim((string) $message->getMessageId(), " \t\n\r\0\x0B<>");

        if ($raw !== '') {
            return mb_substr($raw, 0, 255);
        }

        $fingerprint = hash('sha256', implode('|', [
            (string) $message->getSubject(),
            (string) $message->getFrom(),
            (string) $message->getDate(),
            (string) $message->getSize(),
            $uid,
        ]));

        return 'sha256-'.$fingerprint.'@kargah.invalid';
    }

    /**
     * @return list<RemoteAttachment>
     */
    private function attachments(Message $message): array
    {
        $out = [];

        /** @var Attachment $attachment */
        foreach ($message->getAttachments() as $attachment) {
            $name = trim((string) $attachment->getName());

            if ($name === '') {
                continue;
            }

            $size = $attachment->getSize();

            $out[] = new RemoteAttachment(
                filename: mb_substr($name, 0, 255),
                mime: $this->truncate($attachment->getMimeType(), 190),
                sizeBytes: $size === null ? null : (int) $size,
                contentId: $this->truncate((string) $attachment->getId(), 190),
                partNumber: $this->truncate((string) $attachment->getPartNumber(), 20),
            );
        }

        return $out;
    }

    private function date(Message $message): ?Carbon
    {
        $date = $message->getDate()?->first();

        return $date instanceof \DateTimeInterface ? Carbon::instance($date) : null;
    }

    /**
     * @return list<string>
     */
    private function mails(mixed $attribute): array
    {
        $out = [];

        foreach ($attribute?->all() ?? [] as $address) {
            if ($address instanceof Address && $address->mail !== '') {
                $out[] = $address->mail;
            }
        }

        return array_values(array_unique($out));
    }

    private function header(mixed $attribute): ?string
    {
        $value = trim((string) $attribute);

        return $value === '' ? null : $value;
    }

    private function truncate(?string $value, int $length): ?string
    {
        if ($value === null || trim($value) === '') {
            return null;
        }

        // Column widths, not display widths. A subject longer than its column
        // must not take the whole message down with it.
        return mb_substr($value, 0, $length);
    }
}
