<?php

namespace Modules\Data\Contracts;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Collection;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * The only writer to disk in the entire application.
 *
 * Project, Accounting, Mailbox and Social all need to keep a file against
 * something. None of them opens a file handle: they call this, and Data decides
 * which disk, which path and what gets recorded. That is what makes moving from
 * local storage to S3 one config change instead of a search across five
 * modules — and what makes "where is that file" a question with one answer.
 *
 * **Arrays out, never models.** A caller in Accounting must not receive an
 * `Attachment`; reaching into another module's Eloquent model is the thing that
 * turns a modular monolith back into a monolith. Every method here returns
 * plain arrays with a stable shape, so a rename inside Data cannot break an
 * invoice page.
 *
 * The target goes in as a model because that is what a caller already has, and
 * `getMorphClass()` turns it into the alias this module stores. Nothing about
 * the caller's class leaks into the table.
 *
 * @phpstan-type AttachmentArray array{
 *     id: int, name: string, mime: ?string, size_bytes: int, size: string,
 *     extension: string, checksum: ?string, disk: string, path: string,
 *     target_type: string, target_id: int, uploaded_by: ?int,
 *     uploaded_at: ?string, download_url: string, inline_url: string
 * }
 *
 * Two URLs, and picking the wrong one is a visible bug rather than a style
 * choice. `download_url` sends `Content-Disposition: attachment` — the right
 * answer for a paperclip in a file list, and the wrong one for an `<img src>`,
 * where it asks the browser to save a picture it was only meant to show.
 * `inline_url` is the same bytes behind the same `auth`, displayed. Neither
 * expires; the signed, expiring link is a separate thing, for handing a file to
 * somebody outside.
 */
interface AttachmentService
{
    /**
     * Store an uploaded file against any model and record it.
     *
     * @return array the stored attachment
     */
    public function attach(Model $target, UploadedFile $file, ?int $uploadedBy = null): array;

    /**
     * Store bytes the application generated itself — a rendered invoice PDF, a
     * message body pulled from IMAP — against any model.
     *
     * Separate from `attach()` because an `UploadedFile` carries a client name
     * and a temporary path, and pretending generated bytes are one of those
     * means writing a temp file only to read it straight back.
     */
    public function attachContents(
        Model $target,
        string $contents,
        string $originalName,
        ?string $mime = null,
        ?int $uploadedBy = null,
    ): array;

    /**
     * Everything attached to one target, newest first.
     *
     * @return Collection<int, array>
     */
    public function forTarget(Model $target): Collection;

    /** How many files a target carries, without loading any of them. */
    public function countForTarget(Model $target): int;

    /**
     * The same count for many targets, in **one** query.
     *
     * Exists because `countForTarget()` in a loop is how a page that shows a
     * paperclip on fifty cards issues fifty queries. Project's board search
     * needs to answer "which of these cards have a file" while staying inside a
     * bounded query count, and could not, so `has:attachments` shipped stubbed
     * out until this existed.
     *
     * Keyed `"{morph alias}:{id}"` — the morph alias, never the class name, so
     * a rename inside another module cannot silently produce keys that match
     * nothing. A target with no files is **absent from the array** rather than
     * present with a zero; callers should use `?? 0`.
     *
     * @param  iterable<Model>  $targets
     * @return array<string, int>
     */
    public function countForTargets(iterable $targets): array;

    /**
     * Every id of one morph alias that carries at least one file.
     *
     * The companion to `countForTargets()` for the case where the caller has no
     * models yet — a SQL predicate being built, rather than a page of rows
     * already loaded. `has:attachments` is exactly that: the board's search
     * compiler needs "…and this card has a file" as a `whereIn` **inside** the
     * query that decides which cards to load, so it cannot pass the targets in.
     *
     * Bounded by the number of *attached* things, not by the number of cards:
     * an install with four hundred cards and nine files returns nine ids. That
     * is what makes it safe to pull into PHP, and it is why this returns ids
     * rather than a query builder — a builder would leak Data's own table into
     * a module that is not allowed to know it exists.
     *
     * @param  string  $morphAlias  e.g. `'card'` — the alias, never a class name
     * @return list<int>
     */
    public function targetIdsWithAttachments(string $morphAlias): array;

    /**
     * The bytes of one attachment, or null when the row or its file is gone.
     *
     * `stream()` next door returns a `StreamedResponse`, which is the right
     * answer for a browser and useless to a publisher: getting bytes out of it
     * means capturing output. Social's media pipeline needs the bytes
     * themselves — to hand to a multipart upload, or to `PUT` raw at a network
     * that wants no framing — so it gets its own method rather than reaching
     * for `Storage::disk()` with the `disk` and `path` keys the array happens
     * to publish. That worked, but it put another module's storage layout in
     * another module's hands.
     *
     * A missing file reads as null rather than throwing: an attachment whose
     * bytes have gone is a post that cannot carry that picture, not a request
     * that should 500.
     */
    public function contents(int $attachmentId): ?string;

    /**
     * A readable handle on one attachment's bytes, or null when it is gone.
     *
     * 🔴 **The whole point is that this never puts the file in a string.**
     * `contents()` is right for a picture — a few megabytes, handed to a
     * multipart body, gone at the end of the request. It is exactly wrong for a
     * video: a hundred-megabyte upload read with `contents()` needs a hundred
     * megabytes of `memory_limit`, on shared hosting, inside a queue worker that
     * is also holding a post and its targets. `YouTubePublisher` hands this
     * resource straight to the HTTP client, which reads it in chunks, so the
     * memory cost is the chunk rather than the file.
     *
     * Returns a stream rather than a path for the same reason every other method
     * here returns arrays: the caller must not learn which disk the file is on.
     * A path only exists on a local disk, and answering with one would work
     * today and break the day this install moves to S3 — which is the migration
     * this whole contract exists to keep to one config change.
     *
     * **The caller closes it.** Nothing here holds the handle, because nothing
     * here knows when the upload finishes.
     *
     * @return resource|null
     */
    public function readStream(int $attachmentId);

    /** One attachment, or null when it does not exist or has been deleted. */
    public function find(int $attachmentId): ?array;

    /**
     * A signed, expiring URL that somebody outside this install can fetch.
     *
     * **Not a convenience.** Instagram and Threads will not accept image bytes:
     * their container-create step takes an `image_url` and Meta's own servers go
     * and fetch it, so a picture that only exists behind `auth` cannot be
     * published to either network at all. `inline_url` is permanent and
     * authenticated, which is right for a card cover on your own board and
     * useless here; this is the other thing the class docblock above already
     * named — "the signed, expiring link… for handing a file to somebody
     * outside".
     *
     * The default window is short on purpose. Meta fetches the URL during the
     * container-create call, which is one HTTP round trip away, so half an hour
     * is generous by two orders of magnitude — and the whole point of an expiry
     * is that a URL which leaks stops working. Nothing should raise this to make
     * a link last; a link that needs to last wants `inline_url` and a session.
     *
     * Returns null when the row is gone. It does **not** check that the bytes
     * are still on the disk: that would cost a storage round trip on every
     * attach, and the route behind the signature answers 404 for a missing file
     * anyway — which is the same thing Meta would make of it.
     */
    public function publicUrl(int $attachmentId, int $minutes = 30): ?string;

    /**
     * Stream one attachment to the browser.
     *
     * `$inline` decides between showing it in the tab and offering it as a
     * download; the bytes and the path they come from are identical either way.
     */
    public function stream(int $attachmentId, bool $inline = false): StreamedResponse;

    /**
     * Soft delete an attachment. Returns false when there was nothing to delete.
     *
     * The bytes stay on the disk. A soft-deleted row that pointed at nothing
     * could not be restored, and "undo" is the only reason to soft delete at
     * all — see `purge()` for the version that does remove them.
     */
    public function delete(int $attachmentId): bool;

    /**
     * Remove an attachment and its bytes for good.
     *
     * Deliberately not what the delete button calls.
     */
    public function purge(int $attachmentId): bool;
}
